package oop_final_project;

import java.awt.Color;

import java.sql.ResultSet;
import java.sql.Statement;


import javax.swing.JOptionPane;

public class bg extends javax.swing.JFrame {
    private boolean hasExited;
    private boolean hasClicked;
    JpanelLoader jpload = new JpanelLoader();
    /**
     * Creates new form bg
     */
    public bg() {
        initComponents();
        init();
        remove();
        screen.setOpaque(false);
        name();
        add_user.setEnabled(false);
        Cas.setEnabled(false);
        button();
    }
private void button(){
        String user_name = (login.name);
        Statement stmt;
         try {
            stmt=dbcon.getConnection();
            ResultSet rs= stmt.executeQuery("SELECT * FROM user where user_name ='"+user_name+"'");
             while(rs.next()){
                this.typ.setText(rs.getString(3));
                String ss = typ.getText();
                this.typ.setText("("+rs.getString(3)+")");
                    if(ss.equals("Admin")){
                        add_user.setEnabled(true);
                        Cas.setEnabled(true);
                    }
             }
        } catch (Exception e) {
        }
           
            
    }
private void name(){
    name.setText(login.name);
    
    
    }
private void remove(){
        exit.setOpaque(false);
        exit.setContentAreaFilled(false);
        Add.setOpaque(false);
        Add.setContentAreaFilled(false);
        Cas.setOpaque(false);
        Cas.setContentAreaFilled(false);
        New.setOpaque(false);
        New.setContentAreaFilled(false);
        Dam.setOpaque(false);
        Dam.setContentAreaFilled(false);
        Oth.setOpaque(false);
        Oth.setContentAreaFilled(false);
        Sup.setOpaque(false);
        Sup.setContentAreaFilled(false);
        Sel.setOpaque(false);
        Sel.setContentAreaFilled(false);
        logout.setOpaque(false);
        logout.setContentAreaFilled(false);
        add_user.setOpaque(false);
        add_user.setContentAreaFilled(false);
        
    }
    private void init(){
        setBackground(new Color(0,0,0,0));
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradient1 = new oop_final_project.gradient();
        left_menu1 = new oop_final_project.left_menu();
        Sup = new javax.swing.JButton();
        New = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Dam = new javax.swing.JButton();
        Oth = new javax.swing.JButton();
        Sel = new javax.swing.JButton();
        Cas = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        right_bg1 = new oop_final_project.right_bg();
        screen = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        add_user = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        typ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradient1.setBackground(new java.awt.Color(255, 255, 255));
        gradient1.setPreferredSize(new java.awt.Dimension(1200, 800));
        gradient1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sup.setBackground(new java.awt.Color(153, 153, 153));
        Sup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Sup.setForeground(new java.awt.Color(255, 255, 255));
        Sup.setText("Supplier");
        Sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SupMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SupMouseReleased(evt);
            }
        });
        Sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupActionPerformed(evt);
            }
        });

        New.setBackground(new java.awt.Color(153, 153, 153));
        New.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        New.setForeground(new java.awt.Color(255, 255, 255));
        New.setText("New Goods");
        New.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        New.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewMouseExited(evt);
            }
        });
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(153, 153, 153));
        Add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add Stock");
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Dam.setBackground(new java.awt.Color(153, 153, 153));
        Dam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Dam.setForeground(new java.awt.Color(255, 255, 255));
        Dam.setText("Damaged Goods");
        Dam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DamMouseExited(evt);
            }
        });
        Dam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DamActionPerformed(evt);
            }
        });

        Oth.setBackground(new java.awt.Color(153, 153, 153));
        Oth.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Oth.setForeground(new java.awt.Color(255, 255, 255));
        Oth.setText("Other Expenses");
        Oth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Oth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OthMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OthMouseExited(evt);
            }
        });
        Oth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OthActionPerformed(evt);
            }
        });

        Sel.setBackground(new java.awt.Color(153, 153, 153));
        Sel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Sel.setForeground(new java.awt.Color(255, 255, 255));
        Sel.setText("Selling");
        Sel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SelMouseExited(evt);
            }
        });
        Sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelActionPerformed(evt);
            }
        });

        Cas.setBackground(new java.awt.Color(153, 153, 153));
        Cas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cas.setForeground(new java.awt.Color(255, 255, 255));
        Cas.setText("Cash Book");
        Cas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CasMouseExited(evt);
            }
        });
        Cas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(153, 153, 153));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/city.png"))); // NOI18N

        javax.swing.GroupLayout left_menu1Layout = new javax.swing.GroupLayout(left_menu1);
        left_menu1.setLayout(left_menu1Layout);
        left_menu1Layout.setHorizontalGroup(
            left_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_menu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(left_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(New, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dam, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(Oth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(left_menu1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        left_menu1Layout.setVerticalGroup(
            left_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_menu1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Sup, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dam, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Oth, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        gradient1.add(left_menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -6, 280, 810));

        right_bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        screen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                screenFocusGained(evt);
            }
        });

        javax.swing.GroupLayout screenLayout = new javax.swing.GroupLayout(screen);
        screen.setLayout(screenLayout);
        screenLayout.setHorizontalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        screenLayout.setVerticalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        right_bg1.add(screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 134, -1, -1));

        logout.setBackground(new java.awt.Color(153, 153, 153));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        right_bg1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 46, -1, 33));

        add_user.setBackground(new java.awt.Color(153, 153, 153));
        add_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_user.setForeground(new java.awt.Color(255, 255, 255));
        add_user.setText("Add User");
        add_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_userMouseExited(evt);
            }
        });
        add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_userActionPerformed(evt);
            }
        });
        right_bg1.add(add_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 46, -1, 33));

        name.setFont(new java.awt.Font("AliceLight", 3, 36)); // NOI18N
        name.setForeground(new java.awt.Color(204, 255, 255));
        name.setText("Name");
        right_bg1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 258, -1));

        user.setFont(new java.awt.Font("AliceLight", 3, 36)); // NOI18N
        user.setForeground(new java.awt.Color(204, 255, 255));
        user.setText("Current Worker :");
        right_bg1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 49, 258, -1));

        typ.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        typ.setForeground(new java.awt.Color(255, 204, 204));
        right_bg1.add(typ, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 90, 30));

        gradient1.add(right_bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 940, 800));

        getContentPane().add(gradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        hasClicked=true;
        exit.setOpaque(true);
        exit.setContentAreaFilled(true);
        exit.setBackground(Color.blue);
        int a= JOptionPane.showConfirmDialog(null, "Do you want to exit Application","SELECT",JOptionPane.YES_NO_OPTION);
        if(a==0){
              
            System.exit(0);
        
    }                       
    }//GEN-LAST:event_exitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowGainedFocus

    private void SupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupMouseEntered
        // TODO add your handling code here:
        hasExited =false;
        hasClicked=false;
        Sup.setOpaque(true);
        Sup.setContentAreaFilled(true);
        Sup.setBackground(Color.red);
    }//GEN-LAST:event_SupMouseEntered

    private void SupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupMouseExited
      hasExited =true;
      if(hasExited == true){
          if(hasClicked==true){
            Sup.setOpaque(true);
            Sup.setContentAreaFilled(true);
            Sup.setBackground(Color.blue);
         }else{
        Sup.setOpaque(false);
        Sup.setContentAreaFilled(false);
         }
        
        } else{
         
        
        }
    }//GEN-LAST:event_SupMouseExited

    private void SupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SupMousePressed

    private void SupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SupMouseReleased

    private void SupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupMouseClicked
        // TODO add your handling code here:
        hasClicked=true;
        Sup.setOpaque(true);
        Sup.setContentAreaFilled(true);
        Sup.setBackground(Color.blue);
        exit.setOpaque(false);
        exit.setContentAreaFilled(false);
        Add.setOpaque(false);
        Add.setContentAreaFilled(false);
        Cas.setOpaque(false);
        Cas.setContentAreaFilled(false);
        New.setOpaque(false);
        New.setContentAreaFilled(false);
        Dam.setOpaque(false);
        Dam.setContentAreaFilled(false);
        Oth.setOpaque(false);
        Oth.setContentAreaFilled(false);
        Sel.setOpaque(false);
        Sel.setContentAreaFilled(false);
        
    }//GEN-LAST:event_SupMouseClicked

    private void NewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMouseEntered
        // TODO add your handling code here:
        hasExited =false;
        hasClicked=false;
        New.setOpaque(true);
        New.setContentAreaFilled(true);
        New.setBackground(Color.red);
        
        
    }//GEN-LAST:event_NewMouseEntered

    private void NewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMouseClicked
        // TODO add your handling code here:
        hasClicked=true;
        New.setOpaque(true);
        New.setContentAreaFilled(true);
        New.setBackground(Color.blue);
        
        exit.setOpaque(false);
        exit.setContentAreaFilled(false);
        Add.setOpaque(false);
        Add.setContentAreaFilled(false);
        Cas.setOpaque(false);
        Cas.setContentAreaFilled(false);
        Dam.setOpaque(false);
        Dam.setContentAreaFilled(false);
        Oth.setOpaque(false);
        Oth.setContentAreaFilled(false);
        Sup.setOpaque(false);
        Sup.setContentAreaFilled(false);
        Sel.setOpaque(false);
        Sel.setContentAreaFilled(false);
    }//GEN-LAST:event_NewMouseClicked

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        // TODO add your handling code here:
        hasExited =false;
        hasClicked=false;
        Add.setOpaque(true);
        Add.setContentAreaFilled(true);
        Add.setBackground(Color.red);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        // TODO add your handling code here:
        hasClicked=true;
        Add.setOpaque(true);
        Add.setContentAreaFilled(true);
        Add.setBackground(Color.blue);
        
        exit.setOpaque(false);
        exit.setContentAreaFilled(false);
        Cas.setOpaque(false);
        Cas.setContentAreaFilled(false);
        New.setOpaque(false);
        New.setContentAreaFilled(false);
        Dam.setOpaque(false);
        Dam.setContentAreaFilled(false);
        Oth.setOpaque(false);
        Oth.setContentAreaFilled(false);
        Sup.setOpaque(false);
        Sup.setContentAreaFilled(false);
        Sel.setOpaque(false);
        Sel.setContentAreaFilled(false);
    }//GEN-LAST:event_AddMouseClicked

    private void DamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DamMouseEntered
        // TODO add your handling code here:
        hasExited =false;
        hasClicked=false;
        Dam.setOpaque(true);
        Dam.setContentAreaFilled(true);
        Dam.setBackground(Color.red);
    }//GEN-LAST:event_DamMouseEntered

    private void DamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DamMouseClicked
        // TODO add your handling code here:
        hasClicked=true;
        Dam.setOpaque(true);
        Dam.setContentAreaFilled(true);
        Dam.setBackground(Color.blue);
        
        exit.setOpaque(false);
        exit.setContentAreaFilled(false);
        Add.setOpaque(false);
        Add.setContentAreaFilled(false);
        Cas.setOpaque(false);
        Cas.setContentAreaFilled(false);
        New.setOpaque(false);
        New.setContentAreaFilled(false);
        Oth.setOpaque(false);
        Oth.setContentAreaFilled(false);
        Sup.setOpaque(false);
        Sup.setContentAreaFilled(false);
        Sel.setOpaque(false);
        Sel.setContentAreaFilled(false);
    }//GEN-LAST:event_DamMouseClicked

    private void OthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OthMouseEntered
        // TODO add your handling code here:
        hasExited =false;
        hasClicked=false;
        Oth.setOpaque(true);
        Oth.setContentAreaFilled(true);
        Oth.setBackground(Color.red);
    }//GEN-LAST:event_OthMouseEntered

    private void OthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OthMouseClicked
        // TODO add your handling code here:
        hasClicked=true;
        Oth.setOpaque(true);
        Oth.setContentAreaFilled(true);
        Oth.setBackground(Color.blue);
        
        exit.setOpaque(false);
        exit.setContentAreaFilled(false);
        Add.setOpaque(false);
        Add.setContentAreaFilled(false);
        Cas.setOpaque(false);
        Cas.setContentAreaFilled(false);
        New.setOpaque(false);
        New.setContentAreaFilled(false);
        Dam.setOpaque(false);
        Dam.setContentAreaFilled(false);
        Sup.setOpaque(false);
        Sup.setContentAreaFilled(false);
        Sel.setOpaque(false);
        Sel.setContentAreaFilled(false);
    }//GEN-LAST:event_OthMouseClicked

    private void SelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelMouseEntered
        // TODO add your handling code here:
        hasExited =false;
        hasClicked=false;
        Sel.setOpaque(true);
        Sel.setContentAreaFilled(true);
        Sel.setBackground(Color.red);
    }//GEN-LAST:event_SelMouseEntered

    private void SelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelMouseClicked
        // TODO add your handling code here:
        hasClicked=true;
        Sel.setOpaque(true);
        Sel.setContentAreaFilled(true);
        Sel.setBackground(Color.blue);
        
        exit.setOpaque(false);
        exit.setContentAreaFilled(false);
        Add.setOpaque(false);
        Add.setContentAreaFilled(false);
        Cas.setOpaque(false);
        Cas.setContentAreaFilled(false);
        New.setOpaque(false);
        New.setContentAreaFilled(false);
        Dam.setOpaque(false);
        Dam.setContentAreaFilled(false);
        Oth.setOpaque(false);
        Oth.setContentAreaFilled(false);
        Sup.setOpaque(false);
        Sup.setContentAreaFilled(false);
    }//GEN-LAST:event_SelMouseClicked

    private void CasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasMouseEntered
        // TODO add your handling code here:
        hasExited =false;
        hasClicked=false;
        Cas.setOpaque(true);
        Cas.setContentAreaFilled(true);
        Cas.setBackground(Color.red);
        
        
    }//GEN-LAST:event_CasMouseEntered

    private void CasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasMouseClicked
        // TODO add your handling code here:
        hasClicked=true;
        Cas.setOpaque(true);
        Cas.setContentAreaFilled(true);
        Cas.setBackground(Color.blue);
        
        exit.setOpaque(false);
        exit.setContentAreaFilled(false);
        Add.setOpaque(false);
        Add.setContentAreaFilled(false);
        New.setOpaque(false);
        New.setContentAreaFilled(false);
        Dam.setOpaque(false);
        Dam.setContentAreaFilled(false);
        Oth.setOpaque(false);
        Oth.setContentAreaFilled(false);
        Sup.setOpaque(false);
        Sup.setContentAreaFilled(false);
        Sel.setOpaque(false);
        Sel.setContentAreaFilled(false);
    }//GEN-LAST:event_CasMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        hasExited =false;
        hasClicked=false;
        exit.setOpaque(true);
        exit.setContentAreaFilled(true);
        exit.setBackground(Color.red);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        hasClicked=true;
        exit.setOpaque(true);
        exit.setContentAreaFilled(true);
        exit.setBackground(Color.blue);
        
        
        Add.setContentAreaFilled(false);
        Cas.setContentAreaFilled(false);
        New.setContentAreaFilled(false);
        Dam.setContentAreaFilled(false);
        Oth.setContentAreaFilled(false);
        Sup.setContentAreaFilled(false);
        Sel.setContentAreaFilled(false);
    }//GEN-LAST:event_exitMouseClicked

    private void NewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewMouseExited
        // TODO add your handling code here:
        hasExited =true;
      if(hasExited == true){
          if(hasClicked==true){
            New.setOpaque(true);
            New.setContentAreaFilled(true);
            New.setBackground(Color.blue);
         }else{
        New.setOpaque(false);
        New.setContentAreaFilled(false);
         }
        
        }
    }//GEN-LAST:event_NewMouseExited

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        // TODO add your handling code here:
      hasExited =true;
      if(hasExited == true){
          if(hasClicked==true){
            Add.setOpaque(true);
            Add.setContentAreaFilled(true);
            Add.setBackground(Color.blue);
         }else{
        Add.setOpaque(false);
        Add.setContentAreaFilled(false);
         }
        
        } else{
         
        
        }
    }//GEN-LAST:event_AddMouseExited

    private void DamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DamMouseExited
        // TODO add your handling code here:
        hasExited =true;
      if(hasExited == true){
          if(hasClicked==true){
            Dam.setOpaque(true);
            Dam.setContentAreaFilled(true);
            Dam.setBackground(Color.blue);
         }else{
        Dam.setOpaque(false);
        Dam.setContentAreaFilled(false);
         }
        
        } else{
         
        
        }
    }//GEN-LAST:event_DamMouseExited

    private void OthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OthMouseExited
        // TODO add your handling code here:
        hasExited =true;
      if(hasExited == true){
          if(hasClicked==true){
            Oth.setOpaque(true);
            Oth.setContentAreaFilled(true);
            Oth.setBackground(Color.blue);
         }else{
        Oth.setOpaque(false);
        Oth.setContentAreaFilled(false);
         }
        
        } else{
         
        
        }
    }//GEN-LAST:event_OthMouseExited

    private void SelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelMouseExited
        // TODO add your handling code here:
        hasExited =true;
      if(hasExited == true){
          if(hasClicked==true){
            Sel.setOpaque(true);
            Sel.setContentAreaFilled(true);
            Sel.setBackground(Color.blue);
         }else{
        Sel.setOpaque(false);
        Sel.setContentAreaFilled(false);
         }
        
        } else{
         
        
        }
    }//GEN-LAST:event_SelMouseExited

    private void CasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasMouseExited
        // TODO add your handling code here:
        hasExited =true;
      if(hasExited == true){
          if(hasClicked==true){
            Cas.setOpaque(true);
            Cas.setContentAreaFilled(true);
            Cas.setBackground(Color.blue);
         }else{
        Cas.setOpaque(false);
        Cas.setContentAreaFilled(false);
         }
        
        } else{
         
        
        }
    }//GEN-LAST:event_CasMouseExited

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        hasExited =true;
      if(hasExited == true){
          if(hasClicked==true){
            exit.setOpaque(true);
            exit.setContentAreaFilled(true);
            exit.setBackground(Color.blue);
         }else{
        exit.setOpaque(false);
        exit.setContentAreaFilled(false);
         }
        
        } else{
         
        
        }
    }//GEN-LAST:event_exitMouseExited

    private void SupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupActionPerformed
        // TODO add your handling code here:
        Sup sup =new Sup();
        
        jpload.jPanelLoader(screen, sup);
    }//GEN-LAST:event_SupActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:
        New neww =new New();
        
        jpload.jPanelLoader(screen, neww);
    }//GEN-LAST:event_NewActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        stock add =new stock();
        
        jpload.jPanelLoader(screen, add);
    }//GEN-LAST:event_AddActionPerformed

    private void DamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DamActionPerformed
        // TODO add your handling code here:
        Dam dam =new Dam();
        
        jpload.jPanelLoader(screen, dam);
    }//GEN-LAST:event_DamActionPerformed

    private void OthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OthActionPerformed
        // TODO add your handling code here:
        Oth oth =new Oth();
        
        jpload.jPanelLoader(screen, oth);
    }//GEN-LAST:event_OthActionPerformed

    private void SelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelActionPerformed
        // TODO add your handling code here:
        Sel sel =new Sel();
        
        jpload.jPanelLoader(screen, sel);
    }//GEN-LAST:event_SelActionPerformed

    private void CasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasActionPerformed
        // TODO add your handling code here:
        Cas cas =new Cas();
        
        jpload.jPanelLoader(screen, cas);
    }//GEN-LAST:event_CasActionPerformed

    private void screenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_screenFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_screenFocusGained

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setOpaque(true);
        logout.setContentAreaFilled(true);
        logout.setBackground(Color.red);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setOpaque(false);
        logout.setContentAreaFilled(false);
        
    }//GEN-LAST:event_logoutMouseExited

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int a= JOptionPane.showConfirmDialog(null, "Do you want to Logout?","SELECT",JOptionPane.YES_NO_OPTION);
        if(a==0){
              
        setVisible(false);
        login sp = new login();
        sp.setVisible(true);
        
    }    
       
    }//GEN-LAST:event_logoutActionPerformed

    private void add_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_userMouseEntered
        // TODO add your handling code here:
        add_user.setOpaque(true);
        add_user.setContentAreaFilled(true);
        add_user.setBackground(Color.red);
    }//GEN-LAST:event_add_userMouseEntered

    private void add_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_userMouseExited
        // TODO add your handling code here:
        add_user.setOpaque(false);
        add_user.setContentAreaFilled(false);
    }//GEN-LAST:event_add_userMouseExited

    private void add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_userActionPerformed
        // TODO add your handling code here:
        Add add =new Add();
        
        jpload.jPanelLoader(screen, add);
    }//GEN-LAST:event_add_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Cas;
    private javax.swing.JButton Dam;
    private javax.swing.JButton New;
    private javax.swing.JButton Oth;
    private javax.swing.JButton Sel;
    private javax.swing.JButton Sup;
    private javax.swing.JButton add_user;
    private javax.swing.JButton exit;
    private oop_final_project.gradient gradient1;
    private javax.swing.JLabel jLabel1;
    private oop_final_project.left_menu left_menu1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel name;
    private oop_final_project.right_bg right_bg1;
    private javax.swing.JPanel screen;
    private javax.swing.JLabel typ;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
