/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package oop_final_project;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


import javax.swing.JOptionPane;

/**
 *
 * @author Sandun
 */
public class Cas extends javax.swing.JPanel {
static int expe;
static int inco;
static int last_val;


    /**
     * Creates new form New
     */
    public Cas() {
        initComponents();
        scr.setBackground(new Color(0.0f,0.0f,0.0f,0.3f));
        expbalance();
        incbalance();
        last();
        
       
    }
public void expbalance(){
    
    try{
//        Statement stmt;
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/grocery","root","");
               
                PreparedStatement ptst = (PreparedStatement) conn.prepareStatement("SELECT SUM(price) AS full FROM expenses");
//                stmt=dbcon.getConnection();
                ResultSet rs= ptst.executeQuery();
                while(rs.next()){
                expe=rs.getInt("full"); //Take sum value of total expenses
               
                expens.setText("Rs."+expe);
                }
                
                }catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
        }
    

   
//    try{
//        
//        stmt=dbcon.getConnection();
//        ResultSet rs= stmt.executeQuery("SELECT SUM(DISTINCT price) FROM 'expenses';");
//        
//     
//        while(rs.next()){
//         
//         sum=rs.getInt(3);
//         
//        }
//        expens.setText("Rs."+sum);
//          rs.close();
//    }catch(SQLException k){
//                  
//     }
}


public void incbalance(){
    
    try{

        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/grocery","root","");
               
                PreparedStatement ptst = (PreparedStatement) conn.prepareStatement("SELECT SUM(total) AS full FROM sell");

                ResultSet rs= ptst.executeQuery();
                while(rs.next()){
                inco =rs.getInt("full"); //Take sum value of total Selling items
               
                income.setText("Rs."+inco);
                }
                
                }catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
        }
}

public void last(){
    last_val=inco-expe;
    balance.setText("Rs."+last_val);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        income = new javax.swing.JLabel();
        expens = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        scr.setBackground(new java.awt.Color(51, 51, 51));
        scr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cash Balance");
        scr.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current CashBook Summery");
        scr.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Click Here ");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        scr.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Expenses");
        scr.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Income");
        scr.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        balance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        scr.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 310, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("to More details About Expenses");
        scr.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("Click Here ");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        scr.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("to More details About Incomes");
        scr.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, 20));

        income.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        income.setForeground(new java.awt.Color(255, 255, 255));
        scr.add(income, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 310, 40));

        expens.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        expens.setForeground(new java.awt.Color(255, 255, 255));
        scr.add(expens, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 310, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Expenses exp =new Expenses();
        exp.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        Income inc =new Income();
        inc.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance;
    private javax.swing.JLabel expens;
    private javax.swing.JLabel income;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel scr;
    // End of variables declaration//GEN-END:variables
}
