/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_final_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Sandun
 */
public class Income extends javax.swing.JFrame  {
static int first;
static int last;
static int totall;
static int whole_sales=0;

    /**
     * Creates new form Expenses
     */
    public Income() {
        initComponents();
        showbill();
        cal();
        
    }
private void showbill(){
     
     Statement stmt;
         try{
                stmt=dbcon.getConnection();
                ResultSet rs= stmt.executeQuery("SELECT bill_id FROM sell Limit 1");           //Taking First value of table using descending order
                while(rs.next()){

                    first = rs.getInt("bill_id");
//                    bill_id.setText(String.valueOf(String.format("%05d", bl_id)));                         

}
                  rs.close();
            }catch(SQLException k){
     }
         try{
                stmt=dbcon.getConnection();
                ResultSet rs= stmt.executeQuery("SELECT * FROM sell ORDER BY bill_id DESC LIMIT 1;");           //Taking First value of table using descending order
                while(rs.next()){

                    last = rs.getInt("bill_id");
//                    bill_id.setText(String.valueOf(String.format("%05d", bl_id)));                         

}
                  rs.close();
            }catch(SQLException k){
     } 
//         to.setText(String.valueOf(String.format("%05d", first)));
         
        
       
            
            
        } 

public void cal(){
    
           
 try{
     
     while(first<=last){

        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/grocery","root","");
               String idd= String.valueOf(String.format("%05d", first)); 
                PreparedStatement ptst = (PreparedStatement) conn.prepareStatement("SELECT SUM(total) AS full FROM sell WHERE bill_id='"+idd+"'");
                ResultSet rs= ptst.executeQuery();
                while(rs.next()){
                totall=rs.getInt("full"); //Take sum value of total income
                 }
                
                DefaultTableModel tm=(DefaultTableModel)tablee.getModel();
                tm.setRowCount(first-1);
                Object [] row={idd,totall};
                tm.addRow(row);
                whole_sales=totall+whole_sales; 
                first++;            //Showing Data on table
                
               
     }
     to.setText(String.valueOf(whole_sales));
                
                }catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
        }
       
            
            }


         
         
             
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablee = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        to = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        scr.setBackground(new java.awt.Color(51, 51, 51));
        scr.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 255, 0)));
        scr.setPreferredSize(new java.awt.Dimension(905, 656));
        scr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Incomes");
        scr.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 202, 70));

        tablee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablee);
        if (tablee.getColumnModel().getColumnCount() > 0) {
            tablee.getColumnModel().getColumn(0).setResizable(false);
            tablee.getColumnModel().getColumn(1).setResizable(false);
        }

        scr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 660, 210));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 102));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        scr.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        to.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        to.setForeground(new java.awt.Color(153, 255, 255));
        scr.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 90, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Total");
        scr.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false); //exit Button
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Income.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Income.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Income.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Income.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Income().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel scr;
    private javax.swing.JTable tablee;
    private javax.swing.JLabel to;
    // End of variables declaration//GEN-END:variables
}
