/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package oop_final_project;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Sandun
 */
public class Oth extends javax.swing.JPanel {

    /**
     * Creates new form New
     */
    public Oth() {
        initComponents();
        scr.setBackground(new Color(0.0f,0.0f,0.0f,0.3f));
       
        name();
        table();
    }
    
    public void table(){
    try{
           Class.forName("com.mysql.jdbc.Driver");
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/grocery","root","");
                     
            String sql="SELECT * FROM expenses";
             
            
            PreparedStatement ptst = (PreparedStatement) conn.prepareStatement(sql);
            ResultSet rs=ptst.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)exp_table.getModel();
            tm.setRowCount(0);
            while(rs.next()){
            Object o[]={rs.getString("user"),rs.getString("reason"),rs.getString("price")};
              tm.addRow(o);
            }
        
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
}
private void name(){
    user.setEditable(false);
    user.setText(login.name);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        reason = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        exp_table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scr.setBackground(new java.awt.Color(51, 51, 51));
        scr.setPreferredSize(new java.awt.Dimension(905, 656));
        scr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User");
        scr.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 163, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Other Expenses");
        scr.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 6, 202, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reason");
        scr.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 163, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");
        scr.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 163, 30));
        scr.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 297, 30));
        scr.add(reason, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 297, 30));
        scr.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 297, 30));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        scr.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 100, 30));

        clear.setText("Clear");
        scr.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 100, 30));

        exp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Reason", "Price"
            }
        ));
        jScrollPane1.setViewportView(exp_table);

        scr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 660, 180));

        add(scr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
        Class.forName("com.mysql.jdbc.Driver");
            try (Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/grocery","root","")) {
                String sql="insert into expenses values (?,?,?)";
                PreparedStatement ptst = (PreparedStatement) conn.prepareStatement(sql);
                ptst.setString(1,   user.getText());
                ptst.setString(3,   price.getText());
                ptst.setString(2,   reason.getText());
                
                ptst.executeUpdate();//added expenses details into expenses table
                
                
                String sql2="SELECT * FROM expenses";
                PreparedStatement ptst2 = (PreparedStatement) conn.prepareStatement(sql2);
                ResultSet rs=ptst2.executeQuery();
                DefaultTableModel tm=(DefaultTableModel)exp_table.getModel();
                tm.setRowCount(0);
                while(rs.next()){
                Object o[]={rs.getString("user"),rs.getString("reason"),rs.getString("price")};
                tm.addRow(o);
                }
                JOptionPane.showMessageDialog(null,"Table Updated Successfully");
             }
           price.setText("");
           reason.setText("");
           
                }catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JTable exp_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField reason;
    private javax.swing.JButton save;
    private javax.swing.JPanel scr;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
