/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package oop_final_project;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;



/**
 *
 * @author Sandun
 */
public class Sel extends javax.swing.JPanel {
static int bl_id;
static String val;
static long totalqty;
static  String ss;
    /**
     * Creates new form New
     */
    public Sel() {
        initComponents();
        scr.setBackground(new Color(0.0f,0.0f,0.0f,0.3f));
        name.setEditable(false);
        unit_price.setEditable(false);
        total.setEditable(false);
        user.setEditable(false);
        name();
        bill();
    }
    private void name(){
    user.setEditable(false);
    bill_id.setEditable(false);
    user.setText(login.name); //UnEditable section update
}
    private void bill(){
     
     String str = String.format("%05d", bl_id);
    
     Statement stmt;
         try{
                stmt=dbcon.getConnection();
                ResultSet rs= stmt.executeQuery("SELECT * FROM sell ORDER BY bill_id DESC LIMIT 1;");           //Taking Last value of table using descending order
                while(rs.next()){

                    bl_id = rs.getInt("bill_id");
                    bill_id.setText(String.valueOf(String.format("%05d", bl_id)));                         

}
                  rs.close();
            }catch(SQLException k){

             
       
     }
  
       
             
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        unit_price = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        show = new javax.swing.JButton();
        search = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bill_id = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        neew = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(905, 655));

        scr.setBackground(new java.awt.Color(51, 51, 51));
        scr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                scrFocusGained(evt);
            }
        });
        scr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Billing Section");
        scr.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Goods ID");
        scr.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        scr.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Unit Price");
        scr.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity");
        scr.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total");
        scr.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User");
        scr.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 180, -1));

        id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFocusLost(evt);
            }
        });
        scr.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 364, 36));
        scr.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 364, 36));
        scr.add(unit_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 364, 36));

        quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityFocusLost(evt);
            }
        });
        scr.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 364, 36));
        scr.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 364, 36));
        scr.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 364, 36));

        show.setText("Show Bill");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        scr.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 96, 33));

        search.setText("Search Bills");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        scr.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 96, 30));

        clear.setText("Clear");
        scr.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 96, 33));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bill ID");
        scr.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 180, -1));

        bill_id.setToolTipText("");
        bill_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_idActionPerformed(evt);
            }
        });
        scr.add(bill_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 364, 36));

        add.setText("Add to Bill");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        scr.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 96, 33));

        neew.setText("New Bill");
        neew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neewActionPerformed(evt);
            }
        });
        scr.add(neew, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        Bill bill = new Bill();
        bill.setVisible(true);
    }//GEN-LAST:event_showActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String qty=quantity.getText();
        String iid = id.getText();
        ss =bill_id.getText();
        
        Statement stmt;
    try{
        stmt=dbcon.getConnection();
        ResultSet rs= stmt.executeQuery("SELECT * FROM final_stock where id ='"+iid+"'");
      
        while(rs.next()){
         
         val = rs.getString(3);
         
            if(Long.valueOf(val)>Long.valueOf(qty)){
                totalqty =Long.valueOf(val)-Long.valueOf(qty);
                //do the calculation for last stock value
                                
               }else{
                   JOptionPane.showMessageDialog(null,"Stock Value Too low, please Enter again");
                 
                   quantity.setText("");
                       
               }
         
        }
        
          rs.close();
    }catch(SQLException k){
                  
     }
    if(Long.valueOf(val)>Long.valueOf(qty)){
        try{
        Class.forName("com.mysql.jdbc.Driver");
            try (Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/grocery","root","")) {
                String sql2="UPDATE final_stock SET quantity ="+totalqty+" WHERE id='"+iid+"'";
                PreparedStatement pts = (PreparedStatement) conn.prepareStatement(sql2);
                pts.executeUpdate();  //update calculate value to final stock database
                String sql="insert into sell values (?,?,?,?,?,?,?)";
                PreparedStatement ptst = (PreparedStatement) conn.prepareStatement(sql);
                ptst.setString(1,   bill_id.getText());
                ptst.setString(2,   id.getText());
                ptst.setString(3,   name.getText());
                ptst.setString(4,   unit_price.getText());
                ptst.setString(5,   quantity.getText());
                ptst.setString(6,   total.getText());
                ptst.setString(7,   user.getText());
                ptst.executeUpdate();//added sell goods details into sell table
                
                JOptionPane.showMessageDialog(null,"Added to bill Successfully");
               
                
                   
                
            }
           
           id.setText("");
           name.setText(""); 
           quantity.setText("");
           unit_price.setText("");
           total.setText("");
          
           //clear fields
           
                }catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
        }
        }
       
    }//GEN-LAST:event_addActionPerformed

    private void idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusLost
        // TODO add your handling code here:
        String iid = id.getText();
        Statement stmt;
    try{
        stmt=dbcon.getConnection();
        ResultSet rs= stmt.executeQuery("SELECT * FROM list_of_goods where id ='"+iid+"'");
      
        while(rs.next()){
        this.name.setText(rs.getString(1));
        //getting goods name on list of goods table
        
        }
          rs.close();
    }catch(SQLException k){
                  
     }
    try{
        stmt=dbcon.getConnection();
        ResultSet rs= stmt.executeQuery("SELECT * FROM list_of_goods where id ='"+iid+"'");
      
        while(rs.next()){
        this.unit_price.setText(rs.getString(3));
        //getting unit price on list of goods table
        
        }
          rs.close();
    }catch(SQLException k){
                  
     }
        
    }//GEN-LAST:event_idFocusLost

    private void quantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityFocusLost
        // TODO add your handling code here:
        double val = Double.parseDouble(unit_price.getText());;
        double qty = Double.parseDouble(quantity.getText());
        
        double to= val*qty;
        String total_val = String.valueOf(to);
        total.setText(total_val);
        //Total price calculating
        
    }//GEN-LAST:event_quantityFocusLost

    private void scrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scrFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_scrFocusGained

    private void neewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neewActionPerformed
        // TODO add your handling code here:
        Statement stmt;
                 try{
                        stmt=dbcon.getConnection();
                        ResultSet rs= stmt.executeQuery("SELECT * FROM sell ORDER BY bill_id DESC LIMIT 1;");           //Taking Last value of table using descending order
                        while(rs.next()){
                            
                            bl_id = rs.getInt("bill_id");
                            bl_id=bl_id+1;
                            String str = String.format("%05d", bl_id);
                            if(str=="00000"){
                                str="00001";
                            }
                            bill_id.setText(str);                           //bill id automaticall increase 1 for new record
        
        }
                          rs.close();
                    }catch(SQLException k){

                     }
    }//GEN-LAST:event_neewActionPerformed

    private void bill_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill_idActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        Search search = new Search();
        search.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField bill_id;
    private javax.swing.JButton clear;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField name;
    private javax.swing.JButton neew;
    private javax.swing.JTextField quantity;
    private javax.swing.JPanel scr;
    private javax.swing.JButton search;
    private javax.swing.JButton show;
    private javax.swing.JTextField total;
    private javax.swing.JTextField unit_price;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
