/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package oop_final_project;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandun
 */
public class stock extends javax.swing.JPanel {
static long totalqty;;
    /**
     * Creates new form New
     */
    public stock() {
        initComponents();
        scr.setBackground(new Color(0.0f,0.0f,0.0f,0.3f));
        name();
        name.setEditable(false);
        available.setEditable(false);
       table();
    }
    public void table(){
    try{
           Class.forName("com.mysql.jdbc.Driver");
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/grocery","root","");
                     
            String sql="SELECT * FROM final_stock";
             
            
            PreparedStatement ptst = (PreparedStatement) conn.prepareStatement(sql);
            ResultSet rs=ptst.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)stock_table.getModel();
            tm.setRowCount(0);
            while(rs.next()){
            Object o[]={rs.getString("id"),rs.getString("name"),rs.getString("quantity")};
              tm.addRow(o);
            }
        
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
}
    private void name(){
        user.setEditable(false);
        user.setText(login.name);
        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        available = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        stock_table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        scr.setBackground(new java.awt.Color(51, 51, 51));
        scr.setMinimumSize(new java.awt.Dimension(905, 655));
        scr.setPreferredSize(new java.awt.Dimension(905, 655));
        scr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stock Inventory");
        scr.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 18, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Goods ID");
        scr.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 88, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity");
        scr.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 176, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User");
        scr.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 180, -1));

        id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFocusLost(evt);
            }
        });
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                idMouseExited(evt);
            }
        });
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        scr.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 77, 364, 36));
        scr.add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 220, 370, 36));
        scr.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 173, 364, 36));
        scr.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 270, 370, 36));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        scr.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 96, 33));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        scr.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 96, 33));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Goods Name");
        scr.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 136, 180, -1));
        scr.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 125, 364, 36));

        stock_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Goods ID", "Goods Name", "Total Quantity"
            }
        ));
        jScrollPane1.setViewportView(stock_table);

        scr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 740, 190));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Available Stock");
        scr.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 224, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_idActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String val;
        String qty=quantity.getText();
        String iid=id.getText();
        
        Statement stmt;
                 try{
                        stmt=dbcon.getConnection();
                        ResultSet rs= stmt.executeQuery("SELECT * FROM final_stock where id ='"+iid+"'");
                        while(rs.next()){
                            this.available.setText(rs.getString(3));
                            val=available.getText();
                           
                            totalqty=Long.valueOf(val)+Long.valueOf(qty);
        
        }
                          rs.close();
                    }catch(SQLException k){

                     }          
        try{
        Class.forName("com.mysql.jdbc.Driver");
            try (Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/grocery","root","")) {
                String sql2="UPDATE final_stock SET quantity ="+totalqty+" WHERE id='"+iid+"'";
                PreparedStatement pts = (PreparedStatement) conn.prepareStatement(sql2);
                pts.executeUpdate();
                String sql="insert into stock values (?,?,?,?)";
                PreparedStatement ptst = (PreparedStatement) conn.prepareStatement(sql);
                ptst.setString(1,   id.getText());
                ptst.setString(2,   name.getText());
                ptst.setString(3,   quantity.getText());
                ptst.setString(4,   user.getText());
                ptst.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Data Inserted Successfully");
               
                
                
                String sql3="SELECT * FROM final_stock";
                PreparedStatement ptst2 = (PreparedStatement) conn.prepareStatement(sql3);
                ResultSet rs=ptst2.executeQuery();
                DefaultTableModel tm=(DefaultTableModel)stock_table.getModel();
                tm.setRowCount(0);
                while(rs.next()){
                Object o[]={rs.getString("id"),rs.getString("name"),rs.getString("quantity")};
                tm.addRow(o);                                           //Update  Table
                }    
                
                   
                
            }
           
           id.setText("");
           name.setText(""); 
           quantity.setText("");
           available.setText("");
           
           
                }catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
        }
        
        
            
        
               
    }//GEN-LAST:event_saveActionPerformed

    private void idMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idMouseExited

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idKeyTyped

    private void idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusLost
        // TODO add your handling code here:
        String iid = id.getText();
        Statement stmt;
    try{
        stmt=dbcon.getConnection();
        ResultSet rs= stmt.executeQuery("SELECT * FROM list_of_goods where id ='"+iid+"'");
      
        while(rs.next()){
        this.name.setText(rs.getString(1));
        
        
        }
          rs.close();
    }catch(SQLException k){
                  
     }
    try{
        stmt=dbcon.getConnection();
        ResultSet rs= stmt.executeQuery("SELECT * FROM final_stock where id ='"+iid+"'");
      
        while(rs.next()){
        this.available.setText(rs.getString(3));
        
        
        }
          rs.close();
    }catch(SQLException k){
                  
     }
    }//GEN-LAST:event_idFocusLost

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        id.setText("");
           name.setText(""); 
           quantity.setText("");
           user.setText("");
    }//GEN-LAST:event_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField available;
    private javax.swing.JButton clear;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton save;
    private javax.swing.JPanel scr;
    private javax.swing.JTable stock_table;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
